#application.properties

server.port=8080
spring.config.import=optional:file:.env[.properties]

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.properties.hibernate.dialect=${SPRING.JPA.PROPERTIES.HIBERNATE.DIALECT}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO}

spring.liquibase.enabled=${SPRING_LIQUIBASE_ENABLED}
spring.liquibase.change-log=${SPRING_LIQUIBASE_CHANGELOG}

spring.docker.compose.enabled=false

jwt.expiration-time=${JWT_EXPIRATION_MS}
jwt.secret=${JWT_SECRET}
