driver=com.mysql.cj.jdbc.Driver
url=jdbc:mysql://127.0.0\
  .1:3307/litflix_book_store_db?useSSL=false&allowPublicKeyRetrieval=true\
  &serverTimezone=UTC&characterEncoding=UTF-8
username=user
password=password
changeLogFile=db/changelog/db.changelog-master.yaml

#url=jdbc:mysql://localhost:3306/bookstore_db?serverTimezone=America/Chicago
#username=root
#password=kolobok0202
#changeLogFile=db/changelog/db.changelog-master.yaml
#driver=com.mysql.cj.jdbc.Driver
