driver=com.mysql.cj.jdbc.Driver
url=jdbc:mysql://127.0.0\
  .1:3307/litflix_book_store_db?useSSL=false&allowPublicKeyRetrieval=true\
  &serverTimezone=UTC&characterEncoding=UTF-8
username=user
password=password
changeLogFile=db/changelog/db.changelog-master.yaml
